version: '3.8'
services:
  back:
    build:
      context: ./back
    ports:
      - "5000:5000"
    environment:
      - CURRENT_ENVIRONMENT=development

  front:
    build:
      context: ./front
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=http://back
  